shell = "/usr/bin/tmux"
[window]
dimensions = { columns = 135, lines = 35 }
title = "geez"

# Default colors
[colors.primary]
background = '#363537'
foreground = '#fff1f3'

# Normal colors
[colors.normal]
black   = '#2c2525'
red     = '#fd6883'
green   = '#adda78'
yellow  = '#f9cc6c'
blue    = '#f38d70'
magenta = '#a8a9eb'
cyan    = '#85dacc'
white   = '#fff1f3'

# Bright colors
[colors.bright]
black   = '#72696a'
red     = '#fd6883'
green   = '#adda78'
yellow  = '#f9cc6c'
blue    = '#f38d70'
magenta = '#a8a9eb'
cyan    = '#85dacc'
white   = '#fff1f3'

[colors.dim]
red     = '#d16f8c'
green   = '#7bd88f'
yellow  = '#fd9353'
