# color scheme

terminal.shell = "zsh"
[window]
padding={ x = 5 }
dimensions = { columns = 135, lines = 35 }
title = "geez"
decorations_theme_variant = "Dark"

[font]
normal = { family = "ComicShannsMono Nerd Font", style = "Regular" }
size = 12

[colors.primary]
background = '#32302f'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#e78a4e'
magenta = '#a8a9eb'
cyan    = '#7daea3'
white   = '#fff1f3'

# Bright colors
[colors.bright]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#e78a4e'
magenta = '#a8a9eb'
cyan    = '#7daea3'
white   = '#fff1f3'

[colors.dim]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#e78a4e'
magenta = '#a8a9eb'
cyan    = '#7daea3'
white   = '#fff1f3'

